layers = Layer.create([
  { flavor: 'Vanilla Sponge', pastry_part: 'batter' },
  { flavor: 'Chocolate Sponge', pastry_part: 'batter' },
  { flavor: 'Strawberry Shortcake', pastry_part: 'batter' },
  { flavor: 'Pumpkin', pastry_part: 'batter' },
  { flavor: 'Gingerbread', pastry_part: 'batter' },
  { flavor: 'Red Velvet', pastry_part: 'batter' },
  { flavor: 'Carrot', pastry_part: 'batter' },
  { flavor: 'Lemon', pastry_part: 'batter' },
  { flavor: 'Banana', pastry_part: 'batter'},
  { flavor: 'Marble', pastry_part: 'batter' },
  { flavor: 'Coffee', pastry_part: 'batter' },
  { flavor: 'Buttercream', pastry_part: 'filling' },
  { flavor: 'Chocolate Ganache', pastry_part: 'filling' },
  { flavor: 'Bavarian Cream', pastry_part: 'filling' },
  { flavor: 'Dulce de Leche', pastry_part: 'filling' },
  { flavor: 'Whipped Cream', pastry_part: 'filling' },
  { flavor: 'Keylime Pie', pastry_part: 'filling' },
  { flavor: 'Cream Cheese Frosting', pastry_part: 'filling' },
  { flavor: 'Raspberry Jam', pastry_part: 'filling' },
  { flavor: 'Blueberry Jam', pastry_part: 'filling' },
  { flavor: 'Strawberry Jam', pastry_part: 'filling' },
  { flavor: 'Apricot Preserves', pastry_part: 'filling' }
])