export const CREATE_LAYER_SUCCESS = 'CREATE_LAYER_SUCCESS';
export const CREATE_LAYER_FAILURE = 'CREATE_LAYER_FAILURE';
export const UPDATE_FLAVOR_FORM_DATA = 'UPDATE_FLAVOR_FORM_DATA';
export const RESET_FLAVOR_FORM = 'RESET_FLAVOR_FORM';

export const STACK_LAYER = 'STACK_LAYER';
export const UNSTACK_LAYER = 'UNSTACK_LAYER';
export const SET_LAYERS_SUCCESS = 'SET_LAYERS_SUCCESS';
export const FETCH_LAYERS_FAILURE = 'FETCH_LAYERS_FAILURE';
export const CLEAR_CAKE_CONSTRUCTOR = 'CLEAR_CAKE_CONSTRUCTOR';

export const PROPOSE_PASTRY_SUCCESS = 'PROPOSE_PASTRY_SUCCESS';
export const PROPOSE_PASTRY_FAILURE = 'PROPOSE_PASTRY_FAILURE';
export const SET_CAKES_SUCCESS = 'SET_CAKES_SUCCESS';
export const FETCH_CAKES_FAILURE = 'FETCH_CAKES_FAILURE';