export const STACK_LAYER = 'STACK_LAYER';
export const UNSTACK_LAYER = 'UNSTACK_LAYER';
export const LOAD_LAYERS = 'LOAD_LAYERS';
export const SET_LAYERS_SUCCESS = 'SET_LAYERS_SUCCESS';
export const FETCH_LAYERS_FAILURE = 'FETCH_LAYERS_FAILURE';

export const PURCHASE_PASTRY_PENDING = 'PURCHASE_PASTRY_PENDING';
export const PURCHASE_PASTRY_SUCCESS = 'PURCHASE_PASTRY_SUCCESS';
export const PURCHASE_PASTRY_FAILURE = 'PURCHASE_PASTRY_FAILURE';