export const STACK_LAYER = 'STACK_LAYER';
export const UNSTACK_LAYER = 'UNSTACK_LAYER';
export const SET_LAYERS_SUCCESS = 'SET_LAYERS_SUCCESS';
export const FETCH_LAYERS_FAILURE = 'FETCH_LAYERS_FAILURE';
export const CLEAR_CAKE_CONSTRUCTOR = 'CLEAR_CAKE_CONSTRUCTOR';

export const PURCHASE_PASTRY_SUCCESS = 'PURCHASE_PASTRY_SUCCESS';
export const PURCHASE_PASTRY_FAILURE = 'PURCHASE_PASTRY_FAILURE';
export const SET_CAKES_SUCCESS = 'SET_CAKES_SUCCESS';
export const FETCH_CAKES_FAILURE = 'FETCH_CAKES_FAILURE';